### PR TITLE
update/fix dockerfile

### PR DESCRIPTION
**Pull request by brianlechthaler**
# Summary
* bumped pytorch version to 1.4.0
* bumped torchvision version to 0.5.0
* replaced `apt` with `apt-get` to suppress warning and supposedly make scripted apt more stable
# Notes
Building the image, then `docker run --rm -ti clx:latest ipython` followed by `import cudf` only resulted in hardware-specific errors, as the test build system did not have any graphics cards attached. From this small amount of testing I've concluded this should be stable.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by brianlechthaler** [comment]
> Can one of the admins verify this patch?

Yes, that's definitely a good idea!

**Comment by BartleyR** [comment]
@bsuryadevara Can you review this, especially for our PyTorch dependencies?

**Comment by efajardo-nv** [comment]
This is blocking update to pytorch 1.4.0.
https://github.com/pytorch/pytorch/issues/32584

**Comment by BartleyR** [comment]
> This is blocking update to pytorch 1.4.0.
> [pytorch/pytorch#32584](https://github.com/pytorch/pytorch/issues/32584)

Thanks Eli, I thought there was a blocking update. We won't be able to update to PyTorch 1.4.x until they address this issue.

**Comment by brianlechthaler** [comment]
> This is blocking update to pytorch 1.4.0.
> [pytorch/pytorch#32584](https://github.com/pytorch/pytorch/issues/32584)

Thanks for the feedback, I rolled back PyTorch to version 1.3.1 to ensure compatibility.

**Comment by BartleyR** [comment]
> > This is blocking update to pytorch 1.4.0.
> > [pytorch/pytorch#32584](https://github.com/pytorch/pytorch/issues/32584)
> 
> Thanks for the feedback, I rolled back PyTorch to version 1.3.1 to ensure compatibility.

Awesome, thanks. We'll evaluate and merge.

**Comment by bsuryadevara** [comment]
I got the below error while creating docker image.

```
 ---> Running in 473155c812dc


Examining pytorch:  64%|██████▎   | 267/420 [00:00<00:00, 23513.54it/s]               
Comparing specs that have this dependency:  50%|█████     | 1/2 [01:59<01:59, 119.75s/it]
                                                                                               37it/sUnsatisfiableError: The following specifications were found to be incompatible with each other:       


Package pytorch conflicts for:
pytorch==1.3.1
torchvision=0.5.0 -> pytorch==1.4.0
Package _pytorch_select conflicts for:
pytorch==1.3.1 -> _pytorch_select[version='0.1|0.2']

The command '/bin/bash -c source activate rapids     && conda install -y -c pytorch pytorch==1.3.1 torchvision=0.5.0 datashader>=0.10.* panel=0.6.* geopandas>=0.6.* pyppeteer s3fs     && pip install "git+https://github.com/rapidsai/cudatashader.git"     && cd /rapids/clx     && pip install -e .' returned a non-zero code: 1
```

**Comment by BartleyR** [comment]
> @brianlechthaler I got the below error with `torchvision=0.5.0`. Downgrading to `0.4.2` fixed the issue.
> 
> ```
>  ---> Running in 473155c812dc
> 
> 
> Examining pytorch:  64%|██████▎   | 267/420 [00:00<00:00, 23513.54it/s]               
> Comparing specs that have this dependency:  50%|█████     | 1/2 [01:59<01:59, 119.75s/it]
>                                                                                                37it/sUnsatisfiableError: The following specifications were found to be incompatible with each other:       
> 
> 
> Package pytorch conflicts for:
> pytorch==1.3.1
> torchvision=0.5.0 -> pytorch==1.4.0
> Package _pytorch_select conflicts for:
> pytorch==1.3.1 -> _pytorch_select[version='0.1|0.2']
> 
> The command '/bin/bash -c source activate rapids     && conda install -y -c pytorch pytorch==1.3.1 torchvision=0.5.0 datashader>=0.10.* panel=0.6.* geopandas>=0.6.* pyppeteer s3fs     && pip install "git+https://github.com/rapidsai/cudatashader.git"     && cd /rapids/clx     && pip install -e .' returned a non-zero code: 1
> ```

Thanks Bhargav. Looks like we'll need to then change the version of Torch to `0.4.2`.

**Comment by BartleyR** [comment]
@efajardo-nv Is this PR solved by #159 ?

**Comment by efajardo-nv** [comment]
> @efajardo-nv Is this PR solved by #159 ?

yes, pytorch and torchvision have been updated by #159.

**Comment by BartleyR** [comment]
I'm just going to close this then unless there are objections @brianlechthaler

**Comment by brianlechthaler** [comment]
> I'm just going to close this then unless there are objections @brianlechthaler

No problem, let's close this issue.

**Pull request closed without merging**
