### PR TITLE
Fix to path on cybert notebook

### PR DESCRIPTION
**Pull request by brhodes10**
* Updated path to winevt sample data

### CODE REVIEW

**Comment by BartleyR** [comment]
@brhodes10 Changelog needs to be updated

**Comment by BartleyR** [comment]
Looks fine. Changelog will have to be updated, then we can merge.

**Comment by brhodes10** [comment]
rerun tests

**Comment by brhodes10** [comment]
> Pull from branch 0.12 and update changelog

Complete

**Pull request merged**
