### PR TITLE
removed deprecated function to_array

### PR DESCRIPTION
**Pull request by bsuryadevara**
Replace deprecated function `to_array` with `values_host`

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Comment by bsuryadevara** [comment]
@gpucibot merge

**Comment by bsuryadevara** [comment]
@gpucibot merge

**Comment by Ethyling** [comment]
@gpucibot merge

**Comment by Ethyling** [comment]
We need a review from rapidsai/clx-python-codeowners

**Review by BartleyR — APPROVED** [review]

**Pull request merged**
