### PR TITLE
REVIEW: ABP notebook Training+Inference

### PR DESCRIPTION
**Pull request by gbatmaz**

### CODE REVIEW

**Review by BartleyR — APPROVED** [review]

**Comment by BartleyR** [comment]
rerun tests

**Review by BartleyR — APPROVED** [review]

**Comment by gbatmaz** [comment]
@gpucibot merge

**Comment by gbatmaz** [comment]
@gpucibot merge

**Comment by bsuryadevara** [comment]
@gpucibot merge

**Review by dillon-cullinan — APPROVED** [review]

**Pull request merged**
