### PR TITLE
Remove notebook checkpoint file

### PR DESCRIPTION
**Pull request by brhodes10**
Removed checkpoint file `notebooks/alert_analysis/workflow_implementation/.ipynb_checkpoints/image8-checkpoint.png`

### CODE REVIEW

**Comment by brhodes10** [comment]
rerun tests

**Comment by BartleyR** [comment]
rerun tests

**Comment by brhodes10** [comment]
rerun tests

**Comment by brhodes10** [comment]
rerun tests

**Comment by brhodes10** [comment]
rerun tests

**Pull request merged**
